/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments.index'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as MapsIndexRouteImport } from './routes/maps.index'
import { Route as TournamentsIdRouteImport } from './routes/tournaments.$id'
import { Route as PlayersIdRouteImport } from './routes/players.$id'
import { Route as MapsIdRouteImport } from './routes/maps.$id'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminTournamentsRouteImport } from './routes/_authenticated/admin.tournaments'
import { Route as AuthenticatedAdminPlayersRouteImport } from './routes/_authenticated/admin.players'
import { Route as AuthenticatedAdminMapsRouteImport } from './routes/_authenticated/admin.maps'
import { Route as AuthenticatedAdminInvitesRouteImport } from './routes/_authenticated/admin.invites'
import { Route as AuthenticatedAdminTournamentsIdRouteImport } from './routes/_authenticated/admin.tournaments.$id'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsIndexRoute = MapsIndexRouteImport.update({
  id: '/maps/',
  path: '/maps/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIdRoute = PlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsIdRoute = MapsIdRouteImport.update({
  id: '/maps/$id',
  path: '/maps/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTournamentsRoute =
  AuthenticatedAdminTournamentsRouteImport.update({
    id: '/tournaments',
    path: '/tournaments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlayersRoute =
  AuthenticatedAdminPlayersRouteImport.update({
    id: '/players',
    path: '/players',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMapsRoute = AuthenticatedAdminMapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminInvitesRoute =
  AuthenticatedAdminInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTournamentsIdRoute =
  AuthenticatedAdminTournamentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminTournamentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/stats': typeof StatsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/maps/$id': typeof MapsIdRoute
  '/players/$id': typeof PlayersIdRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/maps/': typeof MapsIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/admin/maps': typeof AuthenticatedAdminMapsRoute
  '/admin/players': typeof AuthenticatedAdminPlayersRoute
  '/admin/tournaments': typeof AuthenticatedAdminTournamentsRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/tournaments/$id': typeof AuthenticatedAdminTournamentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/stats': typeof StatsRoute
  '/join/$token': typeof JoinTokenRoute
  '/maps/$id': typeof MapsIdRoute
  '/players/$id': typeof PlayersIdRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/maps': typeof MapsIndexRoute
  '/players': typeof PlayersIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/admin/maps': typeof AuthenticatedAdminMapsRoute
  '/admin/players': typeof AuthenticatedAdminPlayersRoute
  '/admin/tournaments': typeof AuthenticatedAdminTournamentsRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/tournaments/$id': typeof AuthenticatedAdminTournamentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/stats': typeof StatsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/maps/$id': typeof MapsIdRoute
  '/players/$id': typeof PlayersIdRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/maps/': typeof MapsIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/_authenticated/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/_authenticated/admin/maps': typeof AuthenticatedAdminMapsRoute
  '/_authenticated/admin/players': typeof AuthenticatedAdminPlayersRoute
  '/_authenticated/admin/tournaments': typeof AuthenticatedAdminTournamentsRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/tournaments/$id': typeof AuthenticatedAdminTournamentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/auth'
    | '/compare'
    | '/stats'
    | '/admin'
    | '/join/$token'
    | '/maps/$id'
    | '/players/$id'
    | '/tournaments/$id'
    | '/maps/'
    | '/players/'
    | '/tournaments/'
    | '/admin/invites'
    | '/admin/maps'
    | '/admin/players'
    | '/admin/tournaments'
    | '/admin/'
    | '/admin/tournaments/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/auth'
    | '/compare'
    | '/stats'
    | '/join/$token'
    | '/maps/$id'
    | '/players/$id'
    | '/tournaments/$id'
    | '/maps'
    | '/players'
    | '/tournaments'
    | '/admin/invites'
    | '/admin/maps'
    | '/admin/players'
    | '/admin/tournaments'
    | '/admin'
    | '/admin/tournaments/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/achievements'
    | '/auth'
    | '/compare'
    | '/stats'
    | '/_authenticated/admin'
    | '/join/$token'
    | '/maps/$id'
    | '/players/$id'
    | '/tournaments/$id'
    | '/maps/'
    | '/players/'
    | '/tournaments/'
    | '/_authenticated/admin/invites'
    | '/_authenticated/admin/maps'
    | '/_authenticated/admin/players'
    | '/_authenticated/admin/tournaments'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/tournaments/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AchievementsRoute: typeof AchievementsRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  StatsRoute: typeof StatsRoute
  JoinTokenRoute: typeof JoinTokenRoute
  MapsIdRoute: typeof MapsIdRoute
  PlayersIdRoute: typeof PlayersIdRoute
  TournamentsIdRoute: typeof TournamentsIdRoute
  MapsIndexRoute: typeof MapsIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/': {
      id: '/maps/'
      path: '/maps'
      fullPath: '/maps/'
      preLoaderRoute: typeof MapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id': {
      id: '/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$id': {
      id: '/players/$id'
      path: '/players/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof PlayersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/$id': {
      id: '/maps/$id'
      path: '/maps/$id'
      fullPath: '/maps/$id'
      preLoaderRoute: typeof MapsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tournaments': {
      id: '/_authenticated/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AuthenticatedAdminTournamentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/players': {
      id: '/_authenticated/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AuthenticatedAdminPlayersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/maps': {
      id: '/_authenticated/admin/maps'
      path: '/maps'
      fullPath: '/admin/maps'
      preLoaderRoute: typeof AuthenticatedAdminMapsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invites': {
      id: '/_authenticated/admin/invites'
      path: '/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AuthenticatedAdminInvitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tournaments/$id': {
      id: '/_authenticated/admin/tournaments/$id'
      path: '/$id'
      fullPath: '/admin/tournaments/$id'
      preLoaderRoute: typeof AuthenticatedAdminTournamentsIdRouteImport
      parentRoute: typeof AuthenticatedAdminTournamentsRoute
    }
  }
}

interface AuthenticatedAdminTournamentsRouteChildren {
  AuthenticatedAdminTournamentsIdRoute: typeof AuthenticatedAdminTournamentsIdRoute
}

const AuthenticatedAdminTournamentsRouteChildren: AuthenticatedAdminTournamentsRouteChildren =
  {
    AuthenticatedAdminTournamentsIdRoute: AuthenticatedAdminTournamentsIdRoute,
  }

const AuthenticatedAdminTournamentsRouteWithChildren =
  AuthenticatedAdminTournamentsRoute._addFileChildren(
    AuthenticatedAdminTournamentsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminInvitesRoute: typeof AuthenticatedAdminInvitesRoute
  AuthenticatedAdminMapsRoute: typeof AuthenticatedAdminMapsRoute
  AuthenticatedAdminPlayersRoute: typeof AuthenticatedAdminPlayersRoute
  AuthenticatedAdminTournamentsRoute: typeof AuthenticatedAdminTournamentsRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminInvitesRoute: AuthenticatedAdminInvitesRoute,
  AuthenticatedAdminMapsRoute: AuthenticatedAdminMapsRoute,
  AuthenticatedAdminPlayersRoute: AuthenticatedAdminPlayersRoute,
  AuthenticatedAdminTournamentsRoute:
    AuthenticatedAdminTournamentsRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AchievementsRoute: AchievementsRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  StatsRoute: StatsRoute,
  JoinTokenRoute: JoinTokenRoute,
  MapsIdRoute: MapsIdRoute,
  PlayersIdRoute: PlayersIdRoute,
  TournamentsIdRoute: TournamentsIdRoute,
  MapsIndexRoute: MapsIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
